### ISSUE TITLE
MineOnline LTS

### ISSUE THREAD

**Issue by craftycodie** [craftycodie/MineOnline#254]
Whenever support ends for the MineOnline API, a LTS version of the launcher should be developed.
This will be quite simple, as the MineOnline API doesn't do much these days.

#249 Without the serverlist API, the server list should be saved locally, and players should be able to add servers to the list.
#253 Without the sounds API, all sound packs should be included with LTS releases.

**Comment by craftycodie** [comment]
2 more tasks to do #287 and #275

**Comment by craftycodie** [comment]
TODO LIST:

- [ ] Migrate classic online saves to local.
- [ ] Reimplement the ingame player list.
- [ ] Reimplement server fetching in rich presence
